CREATE TYPE "book_layout" AS ENUM (
    'hardcover',
    'paperback',
    'cards',
    'box_set',
    'pop_up_book',
    'leather_bound',
    'book_with_cd',
    'board_book'
    );

CREATE TYPE "gender" AS ENUM (
    'male',
    'female',
    'others'
    );

CREATE TABLE "categories"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "name"       varchar(256),
    "parent_id"  int
);

CREATE TABLE "category_details"
(
	"id"           int PRIMARY KEY,
	"created_at"   timestamptz,
    "updated_at"   timestamptz,
	"description"  text
);

CREATE TABLE "publishers"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "name"       varchar(256)
);

CREATE TABLE "books"
(
    "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"          timestamptz,
    "updated_at"          timestamptz,
    "name"                text,
    "price"               bigint,
    "discount_percentage" int,
    "discount_amount"     int,
    "average_rating"      real,
    "rating_count"        int,
    "stock"               int,
    "category_id"         int     NOT NULL,
    "delete_status"       boolean NOT NULL,
    "deleted_at"          timestamptz
);

CREATE TABLE "book_details"
(
    "created_at"       timestamptz,
    "updated_at"       timestamptz,
    "id"               int PRIMARY KEY,
    "publisher_id"     int,
    "publication_year" int,
    "weight"           int,
    "book_height"      real,
    "book_width"       real,
    "book_thickness"   real,
    "page_count"       int,
    "layout"           book_layout,
    "description"      text
);

CREATE TABLE "authors"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "name"       varchar(256)
);

CREATE TABLE "book_authors"
(
    "book_id"   int NOT NULL,
    "author_id" int NOT NULL,
    PRIMARY KEY ("book_id", "author_id")
);

CREATE TABLE "book_images"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "book_id"    int NOT NULL,
    "image_path" varchar,
    "order"      int
);

CREATE TABLE "specifications"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "name"       varchar(256)
);

CREATE TABLE "categories_specifications"
(
    "category_id"      int NOT NULL,
    "specification_id" int NOT NULL,
    "is_filtered"      bool,
    PRIMARY KEY ("category_id", "specification_id")
);

CREATE TABLE "books_specifications"
(
    "book_id"          int NOT NULL,
    "specification_id" int NOT NULL,
    "value"            varchar(256),
    PRIMARY KEY ("book_id", "specification_id")
);

CREATE TABLE "accounts"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamptz,
    "updated_at"  timestamptz,
    "email"       varchar(256),
    "password"    varchar(256),
    "first_name"  varchar(256),
    "last_name"   varchar(256),
    "phone"       varchar(10),
    "gender"      gender,
    "birthday"    date,
    "is_verified" boolean,
    "token"       varchar(256),
    "is_oauth2"   boolean
);

CREATE TABLE "provinces"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "code"       varchar(10),
    "name"       varchar(256)
);

CREATE TABLE "districts"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamptz,
    "updated_at"  timestamptz,
    "code"       varchar(10),
    "name"        varchar(256),
    "province_id" int NOT NULL
);

CREATE TABLE "wards"
(
    "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"  timestamptz,
    "updated_at"  timestamptz,
    "code"       varchar(10),
    "name"        varchar(256),
    "district_id" int NOT NULL
);

CREATE TABLE "shipping_addresses"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "address"    text,
    "account_id" int NOT NULL,
    "ward_id"    int NOT NULL,
    "is_default" boolean,
    "can_delete" boolean DEFAULT true
);

CREATE TABLE "cart_items"
(
    "account_id" int NOT NULL,
    "book_id"    int NOT NULL,
    "quantity"   int,
    "price"      int,
    "is_clicked" boolean,
    "state"      smallint,
    PRIMARY KEY ("account_id", "book_id")
);

CREATE TABLE "orders"
(
    "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at"          timestamptz,
    "updated_at"          timestamptz,
    "account_id"          int NOT NULL,
    "shipping_address_id" int NOT NULL,
    "receiver_name"       varchar(256),
    "receiver_phone"      varchar(10),
    "order_time"          timestamptz,
    "total_price"         int,
    "shipping_price"      int,
    "final_price"         int
);

CREATE TABLE "order_details"
(
    "order_id" int NOT NULL,
    "book_id"  int NOT NULL,
    "quantity" int,
    "price"    int,
    PRIMARY KEY ("order_id", "book_id")
);

CREATE TABLE "order_states"
(
    "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "order_id"   int NOT NULL,
    "state"      int
);

CREATE TABLE "reviews"
(
    "book_id"    int NOT NULL,
    "account_id" int NOT NULL,
    "comment"    text,
    "rating"     int,
    "like_count" int,
    PRIMARY KEY ("book_id", "account_id")
);

ALTER TABLE "categories"
    ADD FOREIGN KEY ("parent_id") REFERENCES "categories" ("id");

ALTER TABLE "category_details"
	ADD FOREIGN KEY ("id") REFERENCES "categories" ("id");

ALTER TABLE "books"
    ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "book_details"
    ADD FOREIGN KEY ("id") REFERENCES "books" ("id");

ALTER TABLE "book_details"
    ADD FOREIGN KEY ("publisher_id") REFERENCES "publishers" ("id");

ALTER TABLE "book_authors"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "book_authors"
    ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id");

ALTER TABLE "book_images"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "categories_specifications"
    ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "categories_specifications"
    ADD FOREIGN KEY ("specification_id") REFERENCES "specifications" ("id");

ALTER TABLE "books_specifications"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "books_specifications"
    ADD FOREIGN KEY ("specification_id") REFERENCES "specifications" ("id");

ALTER TABLE "districts"
    ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id");

ALTER TABLE "wards"
    ADD FOREIGN KEY ("district_id") REFERENCES "districts" ("id");

ALTER TABLE "shipping_addresses"
    ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "shipping_addresses"
    ADD FOREIGN KEY ("ward_id") REFERENCES "wards" ("id");

ALTER TABLE "cart_items"
    ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "cart_items"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "orders"
    ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "orders"
    ADD FOREIGN KEY ("shipping_address_id") REFERENCES "shipping_addresses" ("id");

ALTER TABLE "order_details"
    ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_details"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "order_states"
    ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "reviews"
    ADD FOREIGN KEY ("book_id") REFERENCES "books" ("id");

ALTER TABLE "reviews"
    ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
